Stop working around non-nl80211 drivers
Both brcmfmac and old Realtek drivers only support very old hardware:
I don't have any to test it with.

Instead of attempting various heroic workarounds for them, just warn
about them.

diff --git a/create_ap b/create_ap
--- a/create_ap
+++ b/create_ap
@@ -58,7 +58,6 @@ usage() {
     echo "  --timezone              Advertise local timezone in beacons (following 802.11v-2011 7.3.2.87)"
     echo "  --gps <LAT,LNG>         Advertise location in beacons (coordinates are in 10^5 degree)"
     echo "  --freq-band <GHz>       Set frequency band. Valid inputs: 2.4, 5 (default: 2.4)"
-    echo "  --driver                Choose your WiFi adapter driver (default: nl80211)"
     echo "  --no-virt               Do not create virtual interface"
     echo "  --fix-unmanaged         If NetworkManager shows your interface as unmanaged after you"
     echo "                          close create_ap, then use this option to switch your interface"
@@ -110,7 +109,6 @@ usage() {
     echo "  "$PROGNAME" -n wlan0 MyAccessPoint MyPassPhrase"
     echo "  "$PROGNAME" -m bridge wlan0 eth0 MyAccessPoint MyPassPhrase"
     echo "  "$PROGNAME" -m bridge wlan0 br0 MyAccessPoint MyPassPhrase"
-    echo "  "$PROGNAME" --driver rtl871xdrv wlan0 eth0 MyAccessPoint MyPassPhrase"
     echo "  "$PROGNAME" --daemon wlan0 eth0 MyAccessPoint MyPassPhrase"
     echo "  "$PROGNAME" --stop wlan0"
 }
@@ -296,13 +294,6 @@ can_do_80211w() {
 }
 
 can_be_sta_and_ap() {
-    if [[ "$(get_adapter_kernel_module "$1")" == "brcmfmac" ]]; then
-        echo "WARN: brmfmac driver doesn't work properly with virtual interfaces and" >&2
-        echo "      it can cause kernel panic. For this reason we disallow virtual" >&2
-        echo "      interfaces for your adapter." >&2
-        echo "      For more info: https://github.com/oblique/create_ap/issues/203" >&2
-        return 1
-    fi
     get_adapter_info "$1" | grep -E '{.* managed.* AP.*}' > /dev/null 2>&1 && return 0
     get_adapter_info "$1" | grep -E '{.* AP.* managed.*}' > /dev/null 2>&1 && return 0
     return 1
@@ -639,7 +630,6 @@ IEEE80211N=0
 IEEE80211AC=0
 HT_CAPAB='[HT40+]'
 VHT_CAPAB=
-DRIVER=nl80211
 NO_VIRT=0
 COUNTRY=
 TIMEZONE=
@@ -659,7 +649,7 @@ HOSTAPD_DEBUG_ARGS=
 REDIRECT_TO_LOCALHOST=0
 
 CONFIG_OPTS=(CHANNEL GATEWAY WPA_VERSION WEP ETC_HOSTS DHCP_DNS DHCP_DNS6 NO_DNS NO_DNSMASQ HIDDEN MAC_FILTER MAC_FILTER_ACCEPT ISOLATE_CLIENTS
-             SHARE_METHOD IEEE80211N IEEE80211AC HT_CAPAB VHT_CAPAB DRIVER NO_VIRT COUNTRY TIMEZONE GPS FREQ_BAND
+             SHARE_METHOD IEEE80211N IEEE80211AC HT_CAPAB VHT_CAPAB NO_VIRT COUNTRY TIMEZONE GPS FREQ_BAND
              NEW_MACADDR DAEMONIZE DAEMON_PIDFILE DAEMON_LOGFILE WIFI_IFACE INTERNET_IFACE
              SSID PASSPHRASE USE_PSK BEACON_INTERVAL DTIM_PERIOD IPV6 ADDN_HOSTS WPS METERED WEP)
 
@@ -1116,7 +1106,7 @@ for ((i=0; i<$#; i++)); do
     fi
 done
 
-GETOPT_ARGS=$(getopt -o hc:w:g:de:nm: -l "help","hidden","hostapd-debug:","redirect-to-localhost","mac-filter-accept:","mac-filter-deny:","isolate-clients","ieee80211n","ieee80211ac","ht_capab:","vht_capab:","driver:","no-virt","fix-unmanaged","country:","timezone","gps:","freq-band:","mac:","dhcp-dns:","dhcp-dns6:","daemon","pidfile:","logfile:","stop:","list","list-running","list-clients:","version","psk","no-dns","no-dnsmasq","ipv6","mkconfig:","config:","wps","wps-pbc:","wps-pin:","metered","wep" -n "$PROGNAME" -- "$@")
+GETOPT_ARGS=$(getopt -o hc:w:g:de:nm: -l "help","hidden","hostapd-debug:","redirect-to-localhost","mac-filter-accept:","mac-filter-deny:","isolate-clients","ieee80211n","ieee80211ac","ht_capab:","vht_capab:","no-virt","fix-unmanaged","country:","timezone","gps:","freq-band:","mac:","dhcp-dns:","dhcp-dns6:","daemon","pidfile:","logfile:","stop:","list","list-running","list-clients:","version","psk","no-dns","no-dnsmasq","ipv6","mkconfig:","config:","wps","wps-pbc:","wps-pin:","metered","wep" -n "$PROGNAME" -- "$@")
 [[ $? -ne 0 ]] && exit 1
 eval set -- "$GETOPT_ARGS"
 
@@ -1211,11 +1201,6 @@ while :; do
         --vht_capab)
             shift
             VHT_CAPAB="$1"
-            shift
-            ;;
-        --driver)
-            shift
-            DRIVER="$1"
             shift
             ;;
         --no-virt)
@@ -1497,16 +1482,23 @@ if [[ ! -x "$HOSTAPD" ]]; then
     exit 1
 fi
 
-if [[ $(get_adapter_kernel_module ${WIFI_IFACE}) =~ ^(8192[cd][ue]|8723a[sue])$ ]]; then
-    if ! strings "$HOSTAPD" | grep -m1 rtl871xdrv > /dev/null 2>&1; then
-        echo "ERROR: You need to patch your hostapd with rtl871xdrv patches." >&2
-        exit 1
-    fi
-
-    if [[ $DRIVER != "rtl871xdrv" ]]; then
-        echo "WARN: Your adapter needs rtl871xdrv, enabling --driver=rtl871xdrv" >&2
-        DRIVER=rtl871xdrv
-    fi
+WIFI_KMOD="$(get_adapter_kernel_module ${WIFI_IFACE})"
+if [[ "$WIFI_KMOD" =~ ^(8192[cd][ue]|8723a[sue])$ ]]; then
+    echo "WARNING: You are running a very old and buggy wifi driver. It may not work" >&2
+    echo "     at all. See https://github.com/dlenski/create_ap/commit/3460580c" >&2
+    echo >&2
+elif [[ "$WIFI_KMOD" =~ ^rtl[0-9].*$ ]]; then
+    echo "WARNING: You are running a very old and buggy wifi driver. It may not work with" >&2
+    echo "     WPA properly. See https://github.com/dlenski/create_ap/commit/04fa4860" >&2
+    echo >&2
+elif [[ "$WIFI_KMOD" = "rtl871xdrv" ]]; then
+    echo "WARNING: You are running an old and buggy wifi driver. It may not work with" >&2
+    echo "     with iw. See https://github.com/oblique/create_ap/issues/43" >&2
+    echo >&2
+elif [[ "$WIFI_KMOD" = "brcmfmac" ]]; then
+    echo "WARNING: You are running an old and buggy wifi driver. It may not work with" >&2
+    echo "     virtual wifi devices. See https://github.com/oblique/create_ap/issues/203" >&2
+    echo >&2
 fi
 
 HOSTAPD_VER=$($HOSTAPD -v 2>&1 | grep -m1 -oE '[0-9]+(\.[0-9]+)*\.[0-9]+')
@@ -1628,14 +1620,6 @@ if [[ $USE_PSK -eq 0 ]]; then
 elif [[ ${#PASSPHRASE} -gt 0 && ${#PASSPHRASE} -ne 64 ]]; then
     echo "ERROR: Invalid pre-shared-key length ${#PASSPHRASE} (expected 64)" >&2
     exit 1
-fi
-
-if [[ $(get_adapter_kernel_module ${WIFI_IFACE}) =~ ^rtl[0-9].*$ ]]; then
-    if [[ -n "$PASSPHRASE" ]]; then
-        echo "WARN: Realtek drivers usually have problems with WPA1, enabling -w 2" >&2
-        WPA_VERSION=2
-    fi
-    echo "WARN: If AP doesn't work, please read: howto/realtek.md" >&2
 fi
 
 if [[ $NO_VIRT -eq 1 && "$WIFI_IFACE" == "$INTERNET_IFACE" ]]; then
@@ -1787,7 +1771,7 @@ fi
 cat << EOF > $CONFDIR/hostapd.conf
 ssid=${SSID}
 interface=${WIFI_IFACE}
-driver=${DRIVER}
+driver=nl80211
 channel=${CHANNEL}
 ctrl_interface=$CONFDIR/hostapd_ctrl
 ctrl_interface_group=0
@@ -2230,7 +2214,7 @@ echo $HOSTAPD_PID > $CONFDIR/hostapd.pid
 if ! wait $HOSTAPD_PID; then
     echo -e "\nError: Failed to run hostapd, maybe a program is interfering." >&2
     if networkmanager_is_running; then
-        echo "If an error like 'n80211: Could not configure driver mode' was thrown" >&2
+        echo "If an error like 'nl80211: Could not configure driver mode' was thrown" >&2
         echo "try running the following before starting create_ap:" >&2
         if [[ $NM_OLDER_VERSION -eq 1 ]]; then
             echo "    nmcli nm wifi off" >&2
